academia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionario/', include('funcionarios.urls')),
    path('contas/', include('contas.urls')),
    path('cliente/', include('clientes.urls')),
    path('frequencias/', include('frequencias.urls')),
    path('avaliacoes/', include('avaliacoes.urls')),
    path('cliente/mensalidades/', include('mensalidades.urls')),
    path('',views.home, name="home"),
    path('venha-ate-nos/',views.venha_ate_nos, name="venha_ate_nos"),
    path('autorização-negada/',views.autorizacao_negada, name="autorizacao_negada"),
    
]

contas/urls.py
from django.contrib import admin
from django.urls import path, include
from contas import views
from django.conf.urls import url

#from django.contrib.auth.views import LoginView


urlpatterns = [
	path('cadastre-se/', views.registrar_conta, name='registrar_conta'),
	path('login/', views.login_page, name='login_page'),
	path('logout/', views.logout, name='logout'),
	path('alterar-senha/', views.alterar_senha, name='alterar_senha'),
] 	

funcionarios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from funcionarios import views

urlpatterns = [    
    path('cadastrar-funcionario/',views.cadastrar_funcionario, name="cadastrar_funcionario"),
    path('funcionario-cadastrado/',views.cadastro_sucesso, name="cadastro_sucesso"),   
    path('funcionarios-cadastrados/',views.listar_funcionarios, name="listar_funcionarios"), 
    path('excluir-funcionario/<int:id>',views.excluir_funcionario, name="excluir_funcionario"),
    url(r'^matricula-(?P<id>\d+)/$', views.dados_funcionario, name="dados_funcionario"),
    url(r'^editar/matricula-(?P<pk>\d+)/$', views.editar_funcionario, name="editar_funcionario"),
    ]

funcionarios/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core import validators

STATUS = (
        ('ATIVO', 'ATIVO'),
        ('INATIVO', 'INATIVO')        
    )

UF = (
        ('PI', 'PI'),
        ('MA', 'MA'),
        ('AC', 'AC'),
        ('AL', 'AL'),
        ('AM', 'AM'),
        ('AP', 'AP'),
        ('BA', 'BA'),
        ('ES', 'ES'),
        ('CE', 'CE'),
        ('GO', 'GO'),
        ('MT', 'MT'),
        ('MS', 'MS'),
        ('MG', 'MG'),
        ('PA', 'PA'),
        ('PB', 'PB'),
        ('PR', 'PR'),
        ('PE', 'PE'),
        ('RJ', 'RJ'),
        ('RN', 'RN'),
        ('RS', 'RS'),
        ('RO', 'RO'),
        ('RR', 'RR'),
        ('SC', 'SC'),
        ('SP', 'SP'),
        ('SE', 'SE'),
        ('TO', 'TO'),
    )


def validar_cpf(cpf):
    if len(cpf) < 11:
        raise ValidationError("CPF informado não é válido! Quantidade correta de caracteres: 11 dígitos.")

def validar_telefone(telefone):
    if len(telefone) < 12:
        raise ValidationError("Número de telefone inválido! Verifique a quantidade de dígitos informados.")


class Funcionario(models.Model):
	id = models.AutoField(primary_key=True)
	cpf = models.CharField('CPF:', max_length = 11, blank=False, validators=[validar_cpf])
	rg = models.CharField('RG:', max_length = 14, blank=False)
	nome = models.CharField('Nome:', max_length = 100, blank=False)
	nomeGuerra = models.CharField('Nome de guerra: ', max_length = 40, blank=False)
	endereco = models.CharField('Endereço:', max_length = 150, blank=False)
	complemento = models.CharField('Complemento do endereço:', max_length = 150, null=True, blank=True)
	bairro = models.CharField('Bairro:', max_length = 40, blank=False)
	cidade = models.CharField('Cidade:', max_length = 40, blank=False)
	uf = models.CharField('UF:',  choices=UF,max_length = 2, blank=False)
	nascimento = models.DateField('Data de nascimento:', blank = False)
	telefone = models.CharField('Telefone:', max_length = 12, blank=True, null=True, validators=[validar_telefone])
	email = models.EmailField(max_length=70, null=True, blank=True, unique=True)
	dataAdmissao = models.DateField('Data de admissão:', blank = False)
	created_at = models.DateTimeField('Criado em',auto_now_add = True)
	updated_at = models.DateTimeField('Atualizado em',auto_now = True)
	status = models.CharField('Status:', choices=STATUS,max_length = 7, blank=False)
    
	def __str__(self):
		return self.nomeGuerra

	class Meta:
		verbose_name = "Funcionario"
		verbose_name_plural = "Funcionários"
		ordering = ['id','cpf','rg','nome','dataAdmissao','status']	

funcionarios/forms.py
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput
from django import forms
from funcionarios.models import Funcionario

STATUS = (
		('---', '---'),
        ('ATIVO', 'ATIVO'),
        ('INATIVO', 'INATIVO')        
    )

UF = (
		('---', '---'),
        ('PI', 'PI'),
        ('MA', 'MA'),
        ('AC', 'AC'),
        ('AL', 'AL'),
        ('AM', 'AM'),
        ('AP', 'AP'),
        ('BA', 'BA'),
        ('ES', 'ES'),
        ('CE', 'CE'),
        ('GO', 'GO'),
        ('MT', 'MT'),
        ('MS', 'MS'),
        ('MG', 'MG'),
        ('PA', 'PA'),
        ('PB', 'PB'),
        ('PR', 'PR'),
        ('PE', 'PE'),
        ('RJ', 'RJ'),
        ('RN', 'RN'),
        ('RS', 'RS'),
        ('RO', 'RO'),
        ('RR', 'RR'),
        ('SC', 'SC'),
        ('SP', 'SP'),
        ('SE', 'SE'),
        ('TO', 'TO'),
    )


class FuncionarioForm(forms.ModelForm):#TODO retirar o autocomplete dos campos necessários.
    nome = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control form-control-sm text-uppercase','onkeypress':'return isNumericKey(event)','autocomplete':'off','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    nomeGuerra = forms.CharField(max_length=40,widget=forms.TextInput(attrs={'class':'form-control form-control-sm text-uppercase','onkeypress':'return isNumericKey(event)','autocomplete':'off','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    cpf = forms.CharField(max_length=11,widget=forms.TextInput(attrs={'class':'form-control form-control-sm numbers','onkeypress':'return isNumber(event)','autocomplete':'off','placeholder':'000.000.000-00','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    rg = forms.CharField(max_length=14,widget=forms.TextInput(attrs={'class':'form-control form-control-sm','onkeypress':'return isNumber(event)','autocomplete':'off','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    endereco = forms.CharField(max_length=150,widget=forms.TextInput(attrs={'class':'form-control form-control-sm text-uppercase','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    complemento = forms.CharField(max_length=150,required=False,widget=forms.TextInput(attrs={'class':'form-control form-control-sm text-uppercase','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    bairro = forms.CharField(max_length=40,widget=forms.TextInput(attrs={'class':'form-control form-control-sm text-uppercase','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    cidade = forms.CharField(max_length=40,widget=forms.TextInput(attrs={'class':'form-control form-control-sm text-uppercase','onkeypress':'return isNumericKey(event)', 'autocomplete':'off','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    uf = forms.CharField(widget=forms.Select(choices=UF,attrs={'class':'form-control form-control-sm'}))
    nascimento = forms.DateField(widget=DatePickerInput(options={"locale":"pt-br"},format='%d/%m/%Y',attrs={'placeholder':'dd/mm/aaaa','class':'form-control form-control-sm','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    telefone = forms.CharField(max_length=12,required=False,widget=forms.TextInput(attrs={'class':'form-control form-control-sm','onkeypress':'return isNumber(event)', 'autocomplete':'off','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    email = forms.CharField(max_length=70,required=False,widget=forms.TextInput(attrs={'class':'form-control form-control-sm','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    dataAdmissao = forms.DateField(widget=DatePickerInput(options={"locale":"pt-br"},format='%d/%m/%Y',attrs={'placeholder':'dd/mm/aaaa','class':'form-control form-control-sm','oncopy':'return false','onpaste':'return false','ondrop':'return false'}))
    status = forms.CharField(widget=forms.Select(choices=STATUS,attrs={'class':'form-control form-control-sm'}))

    class Meta:
	    model = Funcionario
	    fields = ['nome','nomeGuerra','cpf','rg','endereco','complemento','bairro','cidade','uf','nascimento','telefone','email','dataAdmissao','status']
    

funcionarios/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth.decorators import permission_required
from core import views
from funcionarios.models import Funcionario
from funcionarios.forms import FuncionarioForm


def is_valid_queryparam(param):
    return param != '' and param is not None 

def cadastro_sucesso(request):
	return render(request,'sucesso-cadastro.html')

@permission_required('funcionarios.add_funcionario', login_url=views.autorizacao_negada)
def cadastrar_funcionario(request):
    context = {}    
    template_name = 'cadastrar-funcionario.html'
    if request.method == "POST":
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('http://localhost:8000/funcionario/funcionario-cadastrado')
    else:
        form = FuncionarioForm()
    context['form'] = form
    return render(request, template_name, context)


@permission_required('funcionarios.view_funcionario', login_url=views.autorizacao_negada)
def listar_funcionarios(request):    
    funcionarios = Funcionario.objects.all().order_by('id') 
    funcionarios_ativos = Funcionario.objects.filter(status='ATIVO').count()
    funcionarios_inativos = Funcionario.objects.filter(status='INATIVO').count()
    total_funcionarios = Funcionario.objects.all().count()
    template_name = 'listar-funcionarios.html'
    pesquisar = request.GET.get('pesquisar_funcionario') 
    if is_valid_queryparam(pesquisar):
        funcionarios = funcionarios.filter(nome__icontains=pesquisar) #Pesquisar por objetos que contém a string contida na variável pesquisar.
        total_funcionarios = funcionarios.filter(nome__icontains=pesquisar).count()
    context = {
        'funcionarios': funcionarios, 
        'funcionarios_ativos': funcionarios_ativos,
        'funcionarios_inativos':funcionarios_inativos, 
        'total_funcionarios': total_funcionarios,     
    }

    return render(request, template_name, context)


@permission_required('funcionarios.can_change_Funcionario', login_url=views.autorizacao_negada)
def editar_funcionario(request, pk):
    funcionario = get_object_or_404(Funcionario, pk=pk)
    if request.method == "POST":
        form = FuncionarioForm(request.POST, instance=funcionario)
        if form.is_valid():
            funcionario = form.save(commit=False)
            funcionario.save()
            return redirect('http://localhost:8000/funcionario/funcionarios-cadastrados', pk=funcionario.pk)
    else:
        form = FuncionarioForm(instance=funcionario)
    return render(request, 'editar-funcionario.html', {'form': form })


@permission_required('funcionarios.can_view_Funcionario', login_url=views.autorizacao_negada)
def dados_funcionario(request, id):
    funcionario = get_object_or_404(Funcionario, id=id)
    context = {
    'funcionario':funcionario,
    }
    template_name = 'dados-funcionario.html'
    return render(request, template_name, context)


@permission_required('funcionarios.delete_funcionario', login_url=views.autorizacao_negada)
def excluir_funcionario(request, id):
    funcionario = get_object_or_404(Funcionario, id=id)
    funcionario.delete()
    return redirect(listar_funcionarios)

funcionarios/templates/cadastrar-funcionario.html
{% extends "base.html" %}
{% block content %}
{{ form.media }}

<script type="text/javascript">
	
function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if ( (charCode > 31 && charCode < 48) || charCode > 57) {
            return false;
        }
        return true;
    }

 function isNumericKey(evt)
			{
				var charCode = (evt.which) ? evt.which : evt.keyCode;
				if (charCode != 46 && charCode > 31 
				&& (charCode < 48 || charCode > 57))
				return true;
				return false;
			} 

</script>
<br/><br/><br/>
<div class="container">
	<div class="row">
		<div class="card-body">
			<h3 class="font-weight-bold">Cadastro de novo funcionário</h3><hr/>
			<div class="mx-auto">
				{{ form.non_field_errors }}
				<form method="POST">
					<div class="row">
						{% csrf_token %}
						<div class="col-4">
							
							<label class="font-weight-bold mt-2">Nome&nbsp;<span class="text-danger">*</span></label>
							{{form.nome}}
						</div>					
						<div class="col-2">
							<label class="font-weight-bold mt-2">Nome de guerra&nbsp;<span class="text-danger">*</span></label>
							{{form.nomeGuerra}}
						</div>					
											
						<div class="col-3">
							<label class="font-weight-bold mt-2">CPF&nbsp;<span class="text-danger">*</span></label>
							{{form.cpf}}
						</div>					
						<div class="col-3">
							<label class="font-weight-bold mt-2">RG&nbsp;<span class="text-danger">*</span></label>
							{{form.rg}}
						</div>					
						<div class="col-6">
							<label class="font-weight-bold mt-2">Endereço&nbsp;<span class="text-danger">*</span></label>
							{{form.endereco}}
						</div>
						<div class="col-6">
							<label class="font-weight-bold mt-2">Complemento</label>
							{{form.complemento}}
						</div>
						<div class="col-3">
							<label class="font-weight-bold mt-2">Bairro&nbsp;<span class="text-danger">*</span></label>
							{{form.bairro}}
						</div>
						<div class="col-3">
							<label class="font-weight-bold mt-2">Cidade&nbsp;<span class="text-danger">*</span></label>
							{{form.cidade}}
						</div>
						<div class="col-1">
							<label class="font-weight-bold mt-2">UF&nbsp;<span class="text-danger">*</span></label>
							{{form.uf}}
						</div>
						
						<div class="col-5">
							<label class="font-weight-bold mt-2">E-mail</label>
							{{form.email}}
						</div>
						<div class="col-3">
							<label class="font-weight-bold mt-2">Telefone</label>
							{{form.telefone}}
						</div>
						<div class="col-3">
							<label class="font-weight-bold mt-2">Data de nascimento&nbsp;<span class="text-danger">*</span></label>
							{{form.nascimento}}
						</div>
						<div class="col-3">
							<label class="font-weight-bold mt-2">Data de admissão&nbsp;<span class="text-danger">*</span></label>
							{{form.dataAdmissao}}
						</div>

						<div class="col-3">
							<label class="font-weight-bold mt-2">Status&nbsp;<span class="text-danger">*</span></label>
							{{form.status}}
						</div>

						<div class="caption mt-3 text-muted col-12" role="alert">
							Os campos marcados com <span class="text-danger font-weight-bold">*</span> são de preenchimento obrigatório.
						</div>

						{% if form.errors %}
						<div class="col-12 mt-3 alert alert-danger text-danger font-weight-bold">
							
								{{ form.nome.errors }} 
								{{ form.nomeGuerra.errors }}
								{{ form.cpf.errors }} 
								{{ form.rg.errors }} 
								{{ form.endereco.errors }}
								{{ form.bairro.errors }}
								{{ form.cidade.errors }}
								{{ form.uf.errors }}
								{{ form.nascimento.errors }}
								{{ form.telefone.errors }}
								{{ form.email.errors }}
								{{ form.dataAdmissao.errors }}
								{{ form.status.errors }}
							
						</div>
						{% endif%}

						<div>
							<button type="submit" class="mt-4 btn btn-success"><strong>Cadastrar funcionário</button>
							</div>
					</form>	


				</div>
			</div>
		</div>

	</div>
</div>
</div>
</div>


{% endblock %}

funcionarios/templates/dados-funcionario.html
{% extends "base.html" %}
{% block content %}

<!--

<div class="container">

	 
  <br/>
  
    <p>
       <span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Matrícula: </span>{{ funcionario.id|upper }}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nome completo: </span>{{ funcionario.nome|upper}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nome de guerra: </span>{{ funcionario.nomeGuerra|upper}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CPF: </span>{{ funcionario.cpf}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RG: </span>{{ funcionario.rg}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Endereço: </span>{{ funcionario.endereco|upper}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Complemento: </span>{{ funcionario.complemento|upper}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bairro: </span>{{ funcionario.bairro|upper}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cidade: </span>{{ funcionario.cidade|upper}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UF: </span>{{ funcionario.uf|upper}}<br/>
    	<span class="font-weight-bold">Data de nascimento: </span>{{ funcionario.nascimento|date:"d/m/Y"}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Telefone: </span>{{ funcionario.telefone|upper}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;E-mail: </span>{{ funcionario.email}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;Data de admissão: </span>{{ funcionario.dataAdmissao|date:"d/m/Y"}}<br/>
    	<span class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Status: </span>{{ funcionario.status|upper}}<br/>
<br/>
<span class="text-monospace badge badge-warning float-right">&nbsp;&nbsp;&nbsp;&nbsp;Criado em: {{ funcionario.created_at }}</span><br/>
<span class="text-monospace badge badge-warning float-right">Atualizado em: {{ funcionario.updated_at }}</span>
    </p>

<div class="row">
    
 
    <a href="{% url 'listar_funcionarios' %}" class="btn btn-warning font-weight-bold">Voltar&nbsp;&nbsp;<img src="/static/feather/chevron-left.svg" alt="voltar" class="icone"></a>
    <a href="{% url 'editar_funcionario' pk=funcionario.pk %}" class="ml-2 btn btn-outline-warning font-weight-bold">Editar&nbsp;&nbsp;<img src="/static/feather/edit.svg" alt="editar" class="icone"></a>
  </div>
  </div>

</div>
</div>

-->
<br/><br/><br/>

<div class="container">
        <div class="row col-9 mx-auto">
        <table class="table table-sm table-striped table-bordered">
            <caption class="text-monospace"><small>Cadastrado em: {{ funcionario.created_at }}<br/>Atualizado em: {{ funcionario.updated_at }}</small></caption>
  
  <tbody>
    <tr>
      <th class="text-right">Matrícula:</th>
      <td>{{ funcionario.id|upper }}</td>
      
    </tr>
    <tr>
      <th class="text-right">Nome:</th>
      <td>{{ funcionario.nome|upper}}</td>
    </tr>
    <tr>
      <th class="text-right">Nome de guerra:</th>
      <td>{{ funcionario.nomeGuerra|upper}}</td>
    </tr>
    <tr>
      <th class="text-right">CPF:</th>
      <td>{{ funcionario.cpf }}</td>
    </tr>
    <tr>
      <th class="text-right">RG:</th>
      <td>{{ funcionario.rg}}</td>
    </tr>
    <tr>
      <th class="text-right">Endereço:</th>
      <td>{{ funcionario.endereco|upper }}</td>
    </tr>
    <tr>
      <th class="text-right">Complemento:</th>
      <td>{{ funcionario.complemento|upper }}</td>
    </tr>
    <tr>
      <th class="text-right">Bairro:</th>
      <td>{{ funcionario.bairro|upper}}</td>
    </tr>
    <tr>
      <th class="text-right">Cidade:</th>
      <td>{{ funcionario.cidade|upper}}</td>
    </tr>
    <tr>
      <th class="text-right">UF:</th>
      <td>{{ funcionario.uf|upper}}</td>
    </tr>
    <tr>
      <th class="text-right">Data de nascimento:</th>
      <td>{{ funcionario.nascimento|date:"d/m/Y"}}</td>
    </tr>
    <tr>
      <th class="text-right">Telefone:</th>
      <td>{{ funcionario.telefone|upper}}</td>
    </tr>
    <tr>
      <th class="text-right">Email:</th>
      <td>{{ funcionario.email}}</td>
    </tr>
    <tr>
      <th class="text-right">Data de admissão:</th>
      <td>{{ funcionario.dataAdmissao|date:"d/m/Y"}}</td>
    </tr>
    <tr>
      <th class="text-right">Status:</th>
      <td>{{ funcionario.status|upper}}</td>
    </tr>
  </tbody>
</table>
<div >
       <a href="{% url 'listar_funcionarios' %}" class="btn btn-warning font-weight-bold">Voltar&nbsp;&nbsp;<img src="/static/feather/chevron-left.svg" alt="voltar" class="icone"></a>
       {% if perms.funcionarios.change_funcionario %}
       <a href="{% url 'editar_funcionario' pk=funcionario.pk %}" class="ml-2 btn btn-outline-warning font-weight-bold">Editar&nbsp;&nbsp;<img src="/static/feather/edit.svg" alt="editar" class="icone"></a>
       {% endif%}
       {% if perms.funcionarios.delete_funcionario %}
       <a href="{% url 'excluir_funcionario' id=funcionario.id %}" class="ml-2 btn btn-outline-warning font-weight-bold">Excluir&nbsp;&nbsp;<img src="/static/feather/delete.svg" alt="deletar" class="icone"></a>

       {% endif %}
   </div>
     </div>
     <br/>
     <!---
<div>
    <span class="text-monospace float-right"><small>&nbsp;&nbsp;&nbsp;&nbsp;Criado em: {{ funcionario.created_at }}</small></span><br/>
    <span class="text-monospace float-right"><small>Atualizado em: {{ funcionario.updated_at }}</small></span>
</div>

-->
</div>

</div>
</div>



{% endblock %}