academia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionario/', include('funcionarios.urls')),
    path('contas/', include('contas.urls')),
    path('cliente/', include('clientes.urls')),
    path('frequencias/', include('frequencias.urls')),
    path('avaliacoes/', include('avaliacoes.urls')),
    path('cliente/mensalidades/', include('mensalidades.urls')),
    path('',views.home, name="home"),
    path('venha-ate-nos/',views.venha_ate_nos, name="venha_ate_nos"),
    path('autorização-negada/',views.autorizacao_negada, name="autorizacao_negada"),
    
]

contas/urls.py
from django.contrib import admin
from django.urls import path, include
from contas import views
from django.conf.urls import url

#from django.contrib.auth.views import LoginView


urlpatterns = [
	path('cadastre-se/', views.registrar_conta, name='registrar_conta'),
	path('login/', views.login_page, name='login_page'),
	path('logout/', views.logout, name='logout'),
	path('alterar-senha/', views.alterar_senha, name='alterar_senha'),
] 	

avaliacoes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

CRITERIO = (
	('EQUIPAMENTOS','EQUIPAMENTOS'),
	('ATENDIMENTO','ATENDIMENTO'),
	('INSTRUTORES','INSTRUTORES'),
	('AMBIENTE','AMBIENTE'),
	)



class Avaliacao(models.Model):
	is_avaliado = models.BooleanField(default=False)
	notaCriterio1 = models.IntegerField(default = 0, blank = False, null = True)
	notaCriterio2 = models.IntegerField(default = 0, blank = False, null = True)
	notaCriterio3 = models.IntegerField(default = 0, blank = False, null = True)
	notaCriterio4 = models.IntegerField(default = 0, blank = False, null = True)
	comentario = models.CharField('Comentario', max_length=200, null = True, blank = True)
	criterio1 = models.ForeignKey('Criterio', on_delete=models.CASCADE,related_name='+', blank=True, null=True)
	criterio2 = models.ForeignKey('Criterio', on_delete=models.CASCADE,related_name='+', blank=True, null=True)
	criterio3 = models.ForeignKey('Criterio', on_delete=models.CASCADE,related_name='+', blank=True, null=True)
	criterio4 = models.ForeignKey('Criterio', on_delete=models.CASCADE,related_name='+', blank=True, null=True)
	#avaliador = models.OneToOneField(User, on_delete=models.CASCADE, related_name='usuario_avaliador',null=True, blank= False) 
	avaliador = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, unique=True) 
	created_at = models.DateTimeField('Criado em',auto_now_add = True)
	updated_at = models.DateTimeField('Atualizado em',auto_now = True)


	class Meta:
		verbose_name = "Avaliação"
		verbose_name_plural = "Avaliações"
		ordering = ['is_avaliado','notaCriterio1','notaCriterio2','notaCriterio3','notaCriterio4','comentario','criterio1','criterio2','criterio3','criterio4','avaliador','created_at']



class Criterio(models.Model):
	criterio = models.CharField(choices=CRITERIO, max_length=12, default=None)

	def __str__(self):
		return self.criterio

	class Meta:
		verbose_name = "Critério"
		verbose_name_plural = "Critérios"
		ordering = ['id','criterio']

clientes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core import validators

STATUS = (
        ('ATIVO', 'ATIVO'),
        ('INATIVO', 'INATIVO')        
    )

UF = (
        ('PI', 'PI'),
        ('MA', 'MA'),
        ('AC', 'AC'),
        ('AL', 'AL'),
        ('AM', 'AM'),
        ('AP', 'AP'),
        ('BA', 'BA'),
        ('ES', 'ES'),
        ('CE', 'CE'),
        ('GO', 'GO'),
        ('MT', 'MT'),
        ('MS', 'MS'),
        ('MG', 'MG'),
        ('PA', 'PA'),
        ('PB', 'PB'),
        ('PR', 'PR'),
        ('PE', 'PE'),
        ('RJ', 'RJ'),
        ('RN', 'RN'),
        ('RS', 'RS'),
        ('RO', 'RO'),
        ('RR', 'RR'),
        ('SC', 'SC'),
        ('SP', 'SP'),
        ('SE', 'SE'),
        ('TO', 'TO'),
    )

def validar_cpf(cpf):
    if len(cpf) < 11:
        raise ValidationError("CPF informado não é válido! Quantidade correta de caracteres: 11 dígitos.")

def validar_telefone(telefone):
    if len(telefone) < 12:
        raise ValidationError("Número de telefone inválido! Verifique a quantidade de dígitos informados.")


class Cliente(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    cpf = models.CharField('CPF:', max_length = 11, blank=False, validators=[validar_cpf])
    rg = models.CharField('RG:', max_length = 14, blank=False)
    nome = models.CharField('Nome:', max_length = 100, blank=False)
    endereco = models.CharField('Endereço:', max_length = 150, blank=False)
    complemento = models.CharField('Complemento do endereço:', max_length = 150, null=True, blank=True)
    bairro = models.CharField('Bairro:', max_length = 40, blank=False)
    cidade = models.CharField('Cidade:', max_length = 40, blank=False)
    uf = models.CharField('UF:',  choices=UF,max_length = 2, blank=False)
    nascimento = models.DateField('Data de nascimento:', blank = False)
    telefone = models.CharField('Telefone:', max_length = 12, blank=True, null=True, validators=[validar_telefone])
    email = models.EmailField(max_length=70, null=True, blank=True, unique=True)
    dataInicio = models.DateField('Data de início:', blank = False)
    created_at = models.DateTimeField('Criado em',auto_now_add = True)
    updated_at = models.DateTimeField('Atualizado em',auto_now = True)
    status = models.CharField('Status:', choices=STATUS,max_length = 7, blank=False)
    
    def __str__(self):
	    return self.nome
		
    class Meta:
	    verbose_name = "Cliente"
	    verbose_name_plural = "Clientes"
	    ordering = ['id','cpf','rg','nome','dataInicio','status']	

funcionarios/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core import validators

STATUS = (
        ('ATIVO', 'ATIVO'),
        ('INATIVO', 'INATIVO')        
    )

UF = (
        ('PI', 'PI'),
        ('MA', 'MA'),
        ('AC', 'AC'),
        ('AL', 'AL'),
        ('AM', 'AM'),
        ('AP', 'AP'),
        ('BA', 'BA'),
        ('ES', 'ES'),
        ('CE', 'CE'),
        ('GO', 'GO'),
        ('MT', 'MT'),
        ('MS', 'MS'),
        ('MG', 'MG'),
        ('PA', 'PA'),
        ('PB', 'PB'),
        ('PR', 'PR'),
        ('PE', 'PE'),
        ('RJ', 'RJ'),
        ('RN', 'RN'),
        ('RS', 'RS'),
        ('RO', 'RO'),
        ('RR', 'RR'),
        ('SC', 'SC'),
        ('SP', 'SP'),
        ('SE', 'SE'),
        ('TO', 'TO'),
    )


def validar_cpf(cpf):
    if len(cpf) < 11:
        raise ValidationError("CPF informado não é válido! Quantidade correta de caracteres: 11 dígitos.")

def validar_telefone(telefone):
    if len(telefone) < 12:
        raise ValidationError("Número de telefone inválido! Verifique a quantidade de dígitos informados.")


class Funcionario(models.Model):
	id = models.AutoField(primary_key=True)
	cpf = models.CharField('CPF:', max_length = 11, blank=False, validators=[validar_cpf])
	rg = models.CharField('RG:', max_length = 14, blank=False)
	nome = models.CharField('Nome:', max_length = 100, blank=False)
	nomeGuerra = models.CharField('Nome de guerra: ', max_length = 40, blank=False)
	endereco = models.CharField('Endereço:', max_length = 150, blank=False)
	complemento = models.CharField('Complemento do endereço:', max_length = 150, null=True, blank=True)
	bairro = models.CharField('Bairro:', max_length = 40, blank=False)
	cidade = models.CharField('Cidade:', max_length = 40, blank=False)
	uf = models.CharField('UF:',  choices=UF,max_length = 2, blank=False)
	nascimento = models.DateField('Data de nascimento:', blank = False)
	telefone = models.CharField('Telefone:', max_length = 12, blank=True, null=True, validators=[validar_telefone])
	email = models.EmailField(max_length=70, null=True, blank=True, unique=True)
	dataAdmissao = models.DateField('Data de admissão:', blank = False)
	created_at = models.DateTimeField('Criado em',auto_now_add = True)
	updated_at = models.DateTimeField('Atualizado em',auto_now = True)
	status = models.CharField('Status:', choices=STATUS,max_length = 7, blank=False)
    
	def __str__(self):
		return self.nomeGuerra

	class Meta:
		verbose_name = "Funcionario"
		verbose_name_plural = "Funcionários"
		ordering = ['id','cpf','rg','nome','dataAdmissao','status']	

core/views.py
from django.shortcuts import render


def home(request):
	return render(request,'home.html')

def autorizacao_negada(request):    #Página a ser exibida quando o usuário acessar alguma URL não permitida.
	return render(request,'sem-autorizacao.html')

def venha_ate_nos(request):
	return render(request,'venha-ate-nos.html')

	

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">

<style type="text/css">


  .icone{
   width:22px;
 }

 .background-site
 {
  background: #FFFFFF;
  background-repeat: repeat;
  background-size:100%;
}

.navbar-nav > li > .dropdown-menu { background-color: rgb(255, 250, 250); }
.navbar-nav > li > .dropdown-menu a{   color: #000000;  }
.navbar-nav > li > .dropdown-menu a:hover{   color: #ffffff; background-color: #000000; }

.bg-img{
  background-image: url(/static/img/boxer-1600x1093.png);
  background-repeat: no-repeat;
  background-size: 100%;

}

</style>


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Sistema de gestão para academia de musculação" />
  <title>Academia de musculação</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
</head>
<body class="background-site">
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top " style="background-color: #000000;">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'home' %}">HOME</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse "  id="conteudoNavbarSuportado">
      <ul class="navbar-nav mr-auto">
        {% if perms.funcionarios.view_funcionario or perms.funcionarios.add_funcionario or perms.clientes.view_cliente or perms.clientes.add_cliente %} 
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Cadastros
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if perms.auth.add_user %}
            <a class="dropdown-item" href="{% url 'registrar_conta' %}">Cadastrar senha de acesso</a>
            {% endif %}
            {% if perms.funcionarios.add_funcionario %}
            <a class="dropdown-item" href="{% url 'cadastrar_funcionario' %}">Cadastrar funcionário</a>
            {% endif %}
            {% if perms.clientes.add_cliente %}
            <a class="dropdown-item" href="{% url 'cadastrar_cliente' %}">Cadastrar cliente</a>      
            {% endif %}  
          </li>
          {% endif %}

          {% if perms.clientes.view_cliente or perms.funcionarios.view_funcionario or perms.avaliacoes.view_avaliacao or perms.avaliacoes.add_avaliacao %}
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Relatórios
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if perms.funcionarios.view_funcionario %}
              <a class="dropdown-item" href="{% url 'listar_funcionarios' %}">Listar funcionários</a>  
              {% endif%}
              {% if perms.clientes.view_cliente %}
              <a class="dropdown-item" href="{% url 'listar_clientes' %}">Listar clientes</a>
              {% endif %}
              {% if perms.avaliacoes.view_avaliacao %}
              <a class="dropdown-item" href="{% url 'listar_avaliacoes' %}">Listar avaliações</a>     
              {% endif %}
              {% if perms.avaliacoes.add_avaliacao %}
              <a class="dropdown-item" href="{% url 'minha_avaliacao' %}">Verificar minha avaliação online</a>
              {% endif %}   
            </li>
            {% endif %}
            {% if perms.avaliacoes.add_avaliacao %} 
            <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Atividades
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if perms.avaliacoes.add_avaliacao %}
                <a class="dropdown-item" href="{% url 'avaliar_criterio' %}">Realizar avaliação online</a> 
                <a class="dropdown-item" href="{% url 'minhas_mensalidades' %}">Verificar mensalidades e realizar pagamentos</a> {% endif %}  
                <!--<a class="dropdown-item" href="{% url 'realizar_chamada' %}">Realizar chamada</a> -->
              </li>  
              {% endif%}
              
         

          </ul> 
          {% if not user.is_authenticated %}
          <a href="{% url 'login_page' %}" class="btn btn-outline-light float-right">Realizar login</a>         
          {% else %}
          <div class="btn-group dropleft">
            <button type="button" class="btn btn-outline-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Opções da conta <img src="/static/feather/settings.svg" alt="settings" class="icone">
            </button>
            <div class="dropdown-menu">
              {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'alterar_senha' %}">Alterar senha</a>
              <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>      
              {% endif %}
            </div>
          </div>
          {% endif %}
        </div>
      </nav>

      <script src="/static/js/jquery-3.2.1.min.js"></script>
      <script src="/static/js/popper.min.js"></script>
      <script src="/static/js/bootstrap.min.js"></script>
      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

      <!-- (Optional) Latest compiled and minified JavaScript translation files -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/i18n/defaults-*.min.js"></script>


      {% block content %} {% endblock %} 



    </body>
    </html>

core/templates/home.html
{% extends "base.html" %}
{% block content %}


<!--<img src="/static/img/boxer-1600x1093.png" class="img-fluid bg" alt="Imagem responsiva">-->
<br/><br/>
<div class="container-fluid bg-img">
  <br/>
  <div class="container">
   {% if user.is_authenticated %}
   <div class="alert alert-success">
    <span>
     Olá <span class="badge badge-success">{{ user.username|upper }} </span> seja bem vindo ao sistema de gestão à academia de musculação!
   </span>
 </div>
 <br/><br/><br/><br/><br/><br/>
 {% endif %}

 {% if not user.is_authenticated %}
 <br/>
 <br/>
 <br/>
 <div class="card-deck mb-3 text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><span class="badge badge-pill badge-success">Gratuito!</span></h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">R$ 0,00 <small class="text-muted"></small></h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li>10 dias de academia</li>
        <li>Profissionais qualificados</li>
        <li>Cancelamento a qualquer momento</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
      </ul>
      <a href="{% url 'venha_ate_nos' %}" class="btn btn-lg btn-block btn-success">Matricule-se gratuitamente</a>
    </div>
  </div>
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><span class="badge badge-pill badge-success">Padrão</span></h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">R$ 89,9<small class="text-muted"> Mensais</small></h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li>1 Mês de academia</li>
        <li>Profissionais qualificados</li>
        <li>Acompanhamento de evolução física online</li>
        <li>Pagamentos online via cartão e boleto bancário</li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
      </ul>
      <a href="{% url 'venha_ate_nos' %}" class="btn btn-lg btn-block btn-success">Matricule-se já</a>
    </div>
  </div>
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><span class="badge badge-pill badge-danger">Premium</span></h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">R$ 109,9 <small class="text-muted">Mensais</small></h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li>1 Mês de academia</li>
        <li>Profissionais qualificados</li>
        <li>Acompanhamento de evolução física online</li>
        <li>Pagamentos online via cartão e boleto bancário</li>
        <li>Acomnhamento com nutricionistas</li>
        <li>Acompanhamento com fisioterapeutas</li>
      </ul>
      <a href="{% url 'venha_ate_nos' %}" class="btn btn-lg btn-block btn-danger">Matricule-se já</a>
    </div>
  </div>
</div>

</div>{% endif%}
<br/>
<br/>
<br/>
<br/>
<br/>
</div>
</div>
</div>



<div class="container-flex mt-4">
  <h1 class="text-center font-weight-bold text-info font-italic">Ampla disponibilidade de modalidades</h1>
  <hr/>
  <div class="col-11 mx-auto mt-4">
    <div class="card-deck">
      <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="/static/img/boxe.jpg" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title font-weight-bold text-center text-body">Boxe</h5><hr/>
          <p class="card-text text-justify text-secondary">O boxe ou pugilismo é um esporte de combate, no qual os lutadores usam apenas os punhos, tanto para a defesa, quanto para o ataque.</p>
        </div>
      </div>
      <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="/static/img/musculacao.jpg" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title font-weight-bold text-center text-body">Musculação</h5><hr/>
          <p class="card-text text-justify text-secondary">A musculação é uma modalidade de treinamento físico realizado contra resistência de pesos externos, chamada também de treino resistido, que tem como objetivo o aumento hipertrofia muscular, ganho de força e potência.</p>
        </div>
      </div>
      <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="/static/img/zumba.jpg" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title font-weight-bold text-center text-body">Zumba</h5><hr/>
          <p class="card-text text-justify text-secondary">Zumba é uma modalidade aeróbica que traz mais disposição, modela o corpo e melhora a saúde e o humor de maneira descontraída e cheia de ritmo.</p>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="container-flex">
  <div class="col-11 mx-auto">
    <div class="card-deck">
      <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="/static/img/ginastica.jpg" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title font-weight-bold text-center text-body">Ginástica</h5><hr/>
          <p class="card-text text-justify text-secondary">A ginástica é um conceito que engloba modalidades competitivas e não competitivas e envolve a prática de uma série de movimentos exigentes de força, flexibilidade e coordenação motora para fins únicos de aperfeiçoamento físico e mental.</p>
        </div>
      </div>
      <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="/static/img/pilates.jpg" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title font-weight-bold text-center text-body">Pilates</h5><hr/>
          <p class="card-text text-justify text-secondary">Visa o total e completo controle e conexão entre corpo e mente, devolvendo e restaurando a saúde de indivíduos em condições patológicas assim como promovendo um aumento da qualidade de vida para pessoas saudáveis.</p>
        </div>
      </div>
      <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="/static/img/judo.jpg" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title font-weight-bold text-center text-body">Judô</h5><hr/>
          <p class="card-text text-justify text-secondary"> Os seus principais objetivos são fortalecer o físico, a mente e o espírito de forma integrada, além de desenvolver técnicas de defesa pessoal.</p>
        </div>
      </div>
    </div>
    
  </div>
</div>
<br/>
<br/>
<div class="container">
 <footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-12 col-md">
      <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
      <small class="d-block mb-3 text-muted">&copy; 2019</small>
    </div>
    <div class="col-6 col-md">
      <h5>Redes sociais</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#"><img src="/static/feather/facebook.svg" alt="facebook" class="icone"> &nbsp;&nbsp;Facebook</a></li>
        <li><a class="text-muted" href="#"><img src="/static/feather/instagram.svg" alt="instagram" class="icone"> &nbsp;&nbsp;Instagram</a></li>
        <li><a class="text-muted" href="#"><img src="/static/feather/youtube.svg" alt="youtube" class="icone"> &nbsp;&nbsp;Youtube</a></li>
        <li><a class="text-muted" href="#"><img src="/static/feather/twitter.svg" alt="twitter" class="icone"> &nbsp;&nbsp;Twitter</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Fale conosco</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">academia@academia.com.br</a></li>
        <li><a class="text-muted" href="#">(086) XXXX-XXXX</a></li>
      </ul>
    </div>
    
  </div>
</footer>
</div>


{% endblock %}

core/templates/sem-autorizacao.html
{% extends "base.html" %}
{% block content %}
<br/><br/><br/><br/><br/><br/>
<div class="container">
	<div class="col-8 card mx-auto alert-danger border border-danger">

	<h2 class="card-title mt-2 text-danger">ACESSO NÃO PERMITIDO!</h2><hr/>
	<p class="card-text text-danger ">Usuário não possui os privilégios de sistema necessários para acessar essa página.</p>
	<div class="col-12">
		<a class="btn mb-3 btn-block font-weight-bold btn-danger mx-auto" href="{% url 'home' %}" role="button">Retornar para página inicial</a>

	</div>
</div>
</div>


{% endblock %}

core/templates/sucesso-cadastro-cliente.html
{% extends "base.html" %}
{% block content %}

<br><br><br><br><br><br>
<div class="container card">
<div class="container">

<div class="row">
	<h2 class="font-weight-bold text-dark mx-auto"> Cliente cadastrado com sucesso!</h2>
</div>
</div>
<br>
<div class="container">
	<div class="col-3 mx-auto">
<div class="row">
	<a class="btn btn-success mx-auto" href="{% url 'cadastrar_cliente' %}" role="button">Cadastrar novo cliente</a>
</div>
<div class="row mt-2">
	<a class="btn btn-success mx-auto" href="{% url 'home' %}" role="button">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Página inicial&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
	
</div><br>
</div></div></div>

{% endblock %}

core/templates/sucesso-cadastro.html
{% extends "base.html" %}
{% block content %}

<br><br><br><br><br><br>
<div class="container card">
<div class="container">

<div class="row">
	<h2 class="font-weight-bold text-dark mx-auto"> Funcionário cadastrado com sucesso!</h2>
</div>
</div>
<br>
<div class="container">
	<div class="col-3 mx-auto">
<div class="row">
	<a class="btn btn-success mx-auto" href="{% url 'cadastrar_funcionario' %}" role="button">Cadastrar novo funcionário</a>
</div>
<div class="row mt-2">
	<a class="btn btn-success mx-auto" href="{% url 'home' %}" role="button">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Página inicial&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
	
</div><br>
</div></div></div>

{% endblock %}